server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    # Forzamos el formato JDBC y apuntamos al host
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/academic_events_db
    username: ${DB_USERNAME:ups}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:} 
      url: ${REDIS_URL:}           
  jpa:
    open-in-view: false
    # Agregamos el dialecto explícito para evitar el error de metadata
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# --- CONFIGURACIÓN DE SEGURIDAD JWT ---
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION} 
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

# --- CONFIGURACIÓN DE CORS ---
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}

# Credenciales para acceder a la documentación de Swagger
swagger:
  user: ${SWAGGER_USER_ENV:admin}
  password: ${SWAGGER_PASSWORD_ENV:password123}