server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:} # Se añade password
      url: ${REDIS_URL:}           # Se añade URL por la rúbrica
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

# --- CONFIGURACIÓN DE SEGURIDAD JWT ---
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_ACCESS_EXPIRATION} # coincidir con la rúbrica
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

# --- CONFIGURACIÓN DE CORS ---
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:4200}

# Credenciales para acceder a la documentación de Swagger
swagger:
  user: ${SWAGGER_USER_ENV:evaluador}
  password: ${SWAGGER_PASSWORD_ENV:evaluador123}